application:
  host: "localhost"
  port: 8000
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "postgres"
  database_name: "newsletter"
email:
  sender_email: "hello@asdf.com"
  base_url: "localhost"
  authorization_token: "secret"
