version: '3.6'
services:

  postgres:
    image: postgres:15
    container_name: zero2prod
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=newsletter
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./dbinit/postgres:/docker-entrypoint-initdb.d/:ro
    command: [ "postgres", "-c", "log_statement=all" ]

volumes:
  postgres-data:
